--TABLA USUARIOS
INSERT INTO USUARIOS (NOMBRE_APELLIDO, CEDULA, CORREO_ELECTRONICO, NICK_USUARIO, PASSWORD, ACTIVO, ID_ROL_SISTEMA)
VALUES ('ADMIN', 1234, 'ADMIN', 'ADMIN', 'c4ca4238a0b923820dcc509a6f75849b', 'TRUE', 1);
INSERT INTO USUARIOS (NOMBRE_APELLIDO, CEDULA, CORREO_ELECTRONICO, NICK_USUARIO, PASSWORD, ACTIVO)
VALUES ('FRANCISCO BOGADO', 4156098, 'FRANJABOBE96@GMAIL.COM', 'FJBO96', 'c4ca4238a0b923820dcc509a6f75849b', 'TRUE');
INSERT INTO USUARIOS (NOMBRE_APELLIDO, CEDULA, CORREO_ELECTRONICO, NICK_USUARIO, PASSWORD, ACTIVO, 0)
VALUES ('YANNINA ESQUIVEL', 4269777, 'YANNIESQUIVEL@GMAIL.COM', 'NANNINA', 'c4ca4238a0b923820dcc509a6f75849b', 'TRUE', 1);
INSERT INTO USUARIOS (NOMBRE_APELLIDO, CEDULA, CORREO_ELECTRONICO, NICK_USUARIO, PASSWORD, ACTIVO)
VALUES ('LUIS ZARZA', 4772936, 'LUIS.ZARZA01@GMAIL.COM', 'LUISZARG', 'c4ca4238a0b923820dcc509a6f75849b', 'TRUE', 1);
--OBS: DEFAULT PASSWORD=1

--TABLA ROLES
INSERT INTO ROLES (ID_ROL, NOMBRE, DESCRIPCION) VALUES (0, 'USER','USUARIO DE SITEMA');
INSERT INTO ROLES (NOMBRE, DESCRIPCION) VALUES ('ADM','ADMINISTRADOR DE SISTEMA');
INSERT INTO ROLES (NOMBRE, DESCRIPCION) VALUES ('SCM','SCRUM MASTER');
INSERT INTO ROLES (NOMBRE, DESCRIPCION) VALUES ('PO','PRODUCT OWNER');
INSERT INTO ROLES (NOMBRE, DESCRIPCION) VALUES ('DEV','DEVELOPER');

--TABLA ESTADOS
INSERT INTO ESTADOS (DESCRIPCION) VALUES ('TO-DO');
INSERT INTO ESTADOS (DESCRIPCION) VALUES ('DOING');
INSERT INTO ESTADOS (DESCRIPCION) VALUES ('DONE');
INSERT INTO ESTADOS (DESCRIPCION) VALUES ('SPRINT');
INSERT INTO ESTADOS (DESCRIPCION) VALUES ('PRODUCT');
INSERT INTO ESTADOS (DESCRIPCION) VALUES ('ELIMINADO');
INSERT INTO ESTADOS (DESCRIPCION) VALUES ('INICIADO');
INSERT INTO ESTADOS (DESCRIPCION) VALUES ('FINALIZADO');

--TABLA PRIORIDADES
INSERT INTO PRIORIDADES (DESCRIPCION, NIVEL) VALUES ('HIGH PRIO', 'HP');
INSERT INTO PRIORIDADES (DESCRIPCION, NIVEL) VALUES ('MEDIUM PRIO', 'MP');
INSERT INTO PRIORIDADES (DESCRIPCION, NIVEL) VALUES ('LOW PRIO', 'LP');