--TABLA USUARIOS
INSERT INTO USUARIOS (NOMBRE_APELLIDO, CEDULA, CORREO_ELECTRONICO, NICK_USUARIO, PASSWORD, ACTIVO)
VALUES ('ADMIN', 1234, 'ADMIN', 'ADMIN', '81dc9bdb52d04dc20036dbd8313ed055', 'TRUE');
INSERT INTO USUARIOS (NOMBRE_APELLIDO, CEDULA, CORREO_ELECTRONICO, NICK_USUARIO, PASSWORD, ACTIVO)
VALUES ('FRANCISCO BOGADO', 4156098, 'FRANJABOBE96@GMAIL.COM', 'FJBO96', '81dc9bdb52d04dc20036dbd8313ed055', 'TRUE');
INSERT INTO USUARIOS (NOMBRE_APELLIDO, CEDULA, CORREO_ELECTRONICO, NICK_USUARIO, PASSWORD, ACTIVO)
VALUES ('YANNINA ESQUIVEL', 4269777, 'YANNIESQUIVEL@GMAIL.COM', 'NANNINA', '81dc9bdb52d04dc20036dbd8313ed055', 'TRUE');
INSERT INTO USUARIOS (NOMBRE_APELLIDO, CEDULA, CORREO_ELECTRONICO, NICK_USUARIO, PASSWORD, ACTIVO)
VALUES ('LUIS ZARZA', 4772936, 'LUIS.ZARZA01@GMAIL.COM', 'LUISZARG', '81dc9bdb52d04dc20036dbd8313ed055', 'TRUE');
--OBS: DEFAULT PASSWORD=1234

--TABLA ROLES
INSERT INTO ROLES (NOMBRE, DESCRIPCION) VALUES ('ADM','ADMINISTRADOR');
INSERT INTO ROLES (NOMBRE, DESCRIPCION) VALUES ('SCM','SCRUM MASTER');
INSERT INTO ROLES (NOMBRE, DESCRIPCION) VALUES ('PO','PRODUCT OWNER');
INSERT INTO ROLES (NOMBRE, DESCRIPCION) VALUES ('DEV','DEVELOPER');

--TABLA ESTADOS
INSERT INTO ESTADOS (DESCRIPCION) VALUES ('TO-DO');
INSERT INTO ESTADOS (DESCRIPCION) VALUES ('DOING');
INSERT INTO ESTADOS (DESCRIPCION) VALUES ('DONE');
INSERT INTO ESTADOS (DESCRIPCION) VALUES ('SPRINT');
INSERT INTO ESTADOS (DESCRIPCION) VALUES ('PRODUCT');
INSERT INTO ESTADOS (DESCRIPCION) VALUES ('ELIMINADO');

--TABLA PRIORIDADES
INSERT INTO PRIORIDADES (DESCRIPCION, NIVEL) VALUES ('HIGH PRIO', 'HP');
INSERT INTO PRIORIDADES (DESCRIPCION, NIVEL) VALUES ('MEDIUM PRIO', 'MP');
INSERT INTO PRIORIDADES (DESCRIPCION, NIVEL) VALUES ('LOW PRIO', 'LP');